name: ${project.artifactId}
main: com.jaoafa.AntiAlts3.Main
version: 2021.06.13_14.28
description: サブアカウントのログイン関連を制御するプラグイン
database: true
api-version: 1.16
softdepend: [PermissionsEx, LuckPerms]
author: mine_book000
commands:
   alts:
      description: このプラグインに関する設定や情報が確認できます。
      usage: /<command>
      permission: AntiAlts3.alts
      permission-message: You do not have permission to perform this command.